name:                honeycomb
version:             0.1.0.0
github:              "githubuser/honeycomb"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/honeycomb#readme>

default-extensions:
- GeneralizedNewtypeDeriving
- OverloadedStrings
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- async
- unliftio
- monad-control
- chronos
- aeson
- mtl
- text
- vector
- uuid
- mwc-random
- unordered-containers
- http-client
- http-client-tls
- http-types
- zlib
- bytestring
- stm
- uuid
- auto-update
- microlens
- microlens-mtl
- mmorph
- resource-pool
# TODO split these out
- conduit
- warp
- wai
- vault # needed for wai middleware
- yesod-core
- persistent
- persistent-postgresql
- yesod-persistent
- postgresql-simple
- memory
- cryptonite
- monad-logger
- hostname
- unix
- hashable
- primitive
- exceptions
- resourcet
- http-conduit
- katip

library:
  source-dirs: src

executables:
  honeycomb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honeycomb

tests:
  honeycomb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - honeycomb
